# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dropo User' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Edelivery

pod 'Alamofire'
pod 'Stripe'
pod 'IQKeyboardManagerSwift'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'GoogleSignIn'
pod 'Firebase/Crashlytics'
pod 'Firebase/Database'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Storage'
pod 'Firebase/Messaging'
pod 'SDWebImage'
pod 'Branch'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Core'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'libPhoneNumber-iOS'
pod 'Cosmos'
pod 'SKPhotoBrowser'
pod "TableViewDragger"
pod 'MarqueeLabel'

end



# Disable signing for pods


post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end

